[project]
name = "qt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.16.0",
    "pyside6>=6.9.1",
    "snowflake-connector-python[all]>=3.16.0",
]
